In [160]:
import numpy as np

x = np.random.randint(0,256,1000000)

print(x)
print(np.bincount(x,minlength=256))

[ 51   5  95 ...   4 233 229]
[3793 4009 4058 3916 3861 3804 3855 3843 3974 3807 3892 3903 3938 3860
 4006 3892 3888 3868 4015 3919 3989 3949 3979 3896 3995 3891 3882 3850
 3762 3868 3918 3866 3930 3926 3849 3897 3868 3807 3913 3896 3938 3772
 3814 3958 3865 3921 3983 3945 3825 3840 3840 3868 3979 3955 3913 3910
 3949 3846 3962 4016 3956 3862 3895 3956 3980 3849 3895 3969 3919 3973
 3877 3970 3812 3927 3809 3939 3972 3901 3902 3937 3875 3866 3898 3972
 3932 3962 3914 3935 4009 3994 4025 3871 3760 3865 3897 4057 3885 3936
 3900 3916 3838 3969 3856 3870 3959 3870 3768 3815 3913 3904 4007 3924
 3895 3910 3948 3952 3871 3890 3977 3926 3908 3934 3878 3985 3895 3875
 3837 4006 3949 3947 4016 3862 3912 3874 3895 3899 3922 3878 3926 3890
 3972 3933 3916 3885 3824 4066 3828 3930 3881 3731 3814 3871 3828 3914
 3937 3971 3887 3939 3870 3882 3917 3831 3791 3953 3862 3919 3895 3975
 3895 3922 3940 3796 3938 3815 3879 3996 4011 3955 3868 3864 3974 3950
 3970 3941 4031 3978 3806 3966 3882 3915 3999 3

In [161]:

def get_frequency(image:np.array,num_bins=None):

    image = np.ravel(image)
    bins_range = int(256/num_bins)
    freq = np.bincount(image,minlength=256)

    bin_freq = np.zeros(shape=num_bins)


    for i in range(num_bins-1):
        bin_freq[i] = np.sum(freq[i*bins_range:i*bins_range+bins_range]) # sliding window (window size = bins_range) step = bins_range
    
    i=num_bins-1
    bin_freq[-1]=np.sum(freq[i*bins_range:])
    return bin_freq

def get_frequency2(image: np.array, num_bins: int):
    # Flatten the image into a 1D array
    image = np.ravel(image)
    
    # Calculate the frequency of each pixel value (0-255)
    freq = np.bincount(image, minlength=256)
    
    # Calculate bin ranges
    bins_range = int(256 / num_bins)
    
    # Use np.add.reduceat to sum values for each bin
    indices = np.arange(0, 256, bins_range)
    bin_freq = np.add.reduceat(freq, indices)
    
    # If there are leftover values for the last bin (in case 256 is not divisible by num_bins)
    if len(bin_freq) > num_bins:
        # Merge the last part into the final bin
        bin_freq[-2] += bin_freq[-1]
        bin_freq = bin_freq[:-1]
    
    return bin_freq


In [164]:
for i in range(256):
    print(get_frequency(x,num_bins=5))

[198733. 199974. 199022. 199387. 202884.]
[198733. 199974. 199022. 199387. 202884.]
[198733. 199974. 199022. 199387. 202884.]
[198733. 199974. 199022. 199387. 202884.]
[198733. 199974. 199022. 199387. 202884.]
[198733. 199974. 199022. 199387. 202884.]
[198733. 199974. 199022. 199387. 202884.]
[198733. 199974. 199022. 199387. 202884.]
[198733. 199974. 199022. 199387. 202884.]
[198733. 199974. 199022. 199387. 202884.]
[198733. 199974. 199022. 199387. 202884.]
[198733. 199974. 199022. 199387. 202884.]
[198733. 199974. 199022. 199387. 202884.]
[198733. 199974. 199022. 199387. 202884.]
[198733. 199974. 199022. 199387. 202884.]
[198733. 199974. 199022. 199387. 202884.]
[198733. 199974. 199022. 199387. 202884.]
[198733. 199974. 199022. 199387. 202884.]
[198733. 199974. 199022. 199387. 202884.]
[198733. 199974. 199022. 199387. 202884.]
[198733. 199974. 199022. 199387. 202884.]
[198733. 199974. 199022. 199387. 202884.]
[198733. 199974. 199022. 199387. 202884.]
[198733. 199974. 199022. 199387. 2

In [180]:
s = []
for i in range(4):
    s.append(np.expand_dims(np.arange(5),axis=1))
print(np.concatenate(s))


[[0]
 [1]
 [2]
 [3]
 [4]
 [0]
 [1]
 [2]
 [3]
 [4]
 [0]
 [1]
 [2]
 [3]
 [4]
 [0]
 [1]
 [2]
 [3]
 [4]]
